export const MINIMUM_PLAYERS = 2;
export const MAXIMUM_PLAYERS = 6;
export const ROOM_CODE_LENGTH = 4;
export const DISPLAY_NAME_MAX_LENGTH = 20;
export const RECONNECT_GRACE_MS = 60_000;
export const ROOM_STATUS = Object.freeze({
  LOBBY: "lobby",
  PLAYING: "playing",
  ROUND_COMPLETE: "round_complete",
});
export const ROOM_CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
export const MAX_CODE_ATTEMPTS = 100;

export const ERROR_CODES = Object.freeze({
  INVALID_DISPLAY_NAME: "INVALID_DISPLAY_NAME",
  INVALID_ROOM_CODE: "INVALID_ROOM_CODE",
  ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  ROOM_FULL: "ROOM_FULL",
  ROOM_NOT_JOINABLE: "ROOM_NOT_JOINABLE",
  DISPLAY_NAME_TAKEN: "DISPLAY_NAME_TAKEN",
  INVALID_SESSION: "INVALID_SESSION",
  NOT_IN_ROOM: "NOT_IN_ROOM",
  NOT_HOST: "NOT_HOST",
  CANNOT_KICK_SELF: "CANNOT_KICK_SELF",
  PLAYER_NOT_FOUND: "PLAYER_NOT_FOUND",
});
